agent:
  id: "ENG-WS-01"
  name: "Engineering-WS-01"
  watch_paths:
    - "C:\\Users\\Public"
    - "C:\\ProgramData"
  ext_watchlist: [".lockbit",".conti",".encrypted",".ryk",".lkr"]
  file_burst_threshold_per_sec: 120

outbound:
  mode: "mqtt"   # "mqtt" or "https"
  mqtt:
    host: "localhost"
    port: 8883
    username: "rtm_agent"
    password: "REDACTED"
    cafile: "..\\deploy\\tls\\ca.crt"
  https:
    url: "https://127.0.0.1:8000/ingest"
    cafile: "..\\deploy\\tls\\ca.crt"

security:
  hmac_key_env: "RTM_HMAC_KEY"
