agent:
  id: "RANSOMWARE-PROTECTOR"
  name: "Windows-Ransomware-Defense"
  watch_paths:
    - "C:\\Users\\Public"
    - "C:\\ProgramData"
  ext_watchlist: [".lockbit", ".conti", ".encrypted", ".ryk", ".lkr"]
  file_burst_threshold_per_sec: 120

outbound:
  mode: "https"   # we're using the FastAPI collector (app.py), no MQTT
  https:
    url: "http://127.0.0.1:8000/ingest"  # plain HTTP for local testing
    cafile: ""                           # leave blank since it's HTTP (no TLS)

  # keeping mqtt section for later if you want to switch back
  mqtt:
    host: "localhost"
    port: 8883
    username: "rtm_agent"
    password: "REDACTED"
    cafile: "..\\deploy\\tls\\ca.crt"

security:
  hmac_key_env: "RTM_HMAC_KEY"
