agent:
  id: "RANSOMWARE-PROTECTOR"
  name: "Windows-Ransomware-Defense"
  watch_paths:
    - "C:\\Users\\sakindu\\Downloads\\testing\\"
  ext_watchlist: [".lockbit", ".conti", ".encrypted", ".ryk", ".lkr"]
  file_burst_threshold_per_sec: 100
  # CPU usage percentage threshold above which a process will be flagged
  cpu_usage_threshold: 90
  # Disk write threshold (bytes/sec) above which a process will be flagged
  io_write_threshold_bytes: 157286400  # 50 MB/s

  quarantine_on_create:
      enable: true
      paths:
        - "C:\\Users\\sakindu\\Downloads\\testing"
      # File types to quarantine on drop (extend as needed)
      exts: [".exe", ".dll", ".scr", ".js", ".vbs", ".ps1", ".hta", ".jar", ".bat", ".cmd"]

outbound:
  mode: "https"   # we're using the FastAPI collector (app.py), no MQTT
  https:
    url: "http://127.0.0.1:8000/ingest"  # plain HTTP for local testing
    cafile: ""                           # leave blank since it's HTTP (no TLS)

  # keeping mqtt section for later if you want to switch back
  mqtt:
    host: "localhost"
    port: 8883
    username: "rtm_agent"
    password: "REDACTED"
    cafile: "..\\deploy\\tls\\ca.crt"

security:
  hmac_key_env: "RTM_HMAC_KEY"
