agent:
  id: "RANSOMWARE-PROTECTOR"
  name: "Windows-Ransomware-Defense"

  # Monitored system locations (realistic + test folder)
  watch_paths:
    - "C:\\Users\\Public"
    - "C:\\ProgramData"
    - "C:\\Temp"
  # Common ransomware extension watchlist
  ext_watchlist:
    - ".lockbit"
    - ".conti"
    - ".encrypted"
    - ".ryk"
    - ".lkr"
    - ".wnry"
    - ".wncry"
    - ".wcry"

  # Detection thresholds
  file_burst_threshold_per_sec: 100          # triggers if >100 file ops/sec
  entropy_threshold: 7.5                     # heuristic for encrypted data
  cpu_usage_threshold: 85                    # % CPU threshold
  io_write_threshold_bytes: 104857600        # 100 MB/s disk write

  # Containment: quarantine suspicious executables dropped in watched paths
  quarantine_on_create:
    enable: true
    paths:
      - "C:\\Users\\Public"
      - "C:\\ProgramData"
    exts:
      - ".exe"
      - ".dll"
      - ".scr"
      - ".js"
      - ".vbs"
      - ".ps1"
      - ".hta"
      - ".jar"
      - ".bat"
      - ".cmd"

outbound:
  mode: "https"                             # use HTTPS collector (FastAPI backend)
  https:
    url: "http://127.0.0.1:8000/ingest"     # must end with /ingest
    cafile: ""                              # blank = no TLS for local testing
  mqtt:                                     # retained for future use
    host: "localhost"
    port: 8883
    username: "rtm_agent"
    password: "REDACTED"
    cafile: "..\\deploy\\tls\\ca.crt"

security:
  # HMAC key is provided via environment variable for integrity of agent <-> backend
  hmac_key_env: "RTM_HMAC_KEY"
