agent:
  id: "RANSOMWARE-PROTECTOR"
  name: "Windows-Ransomware-Defense"

  # Monitor realistic system locations + a local test folder
  watch_paths:
    - "C:\\Users\\Public"
    - "C:\\ProgramData"
    - "C:\\Users\\sakindu\\Downloads\\testing\\"

  # Expanded ransomware extension watchlist
  ext_watchlist:
    - ".lockbit"
    - ".conti"
    - ".encrypted"
    - ".ryk"
    - ".lkr"
    - ".wnry"
    - ".wncry"
    - ".wcry"

  # Tuned thresholds (balanced sensitivity)
  file_burst_threshold_per_sec: 100        # more sensitive to rapid file ops
  entropy_threshold: 7.5                   # keep for encrypted-content heuristics
  cpu_usage_threshold: 85                  # warn sooner without being noisy
  io_write_threshold_bytes: 104857600      # 100 MB/s (balanced vs 50/150)

  # Optional containment: quarantine risky executables on drop in watched paths
  quarantine_on_create:
    enable: true
    paths:
      - "C:\\Users\\Public"
      - "C:\\ProgramData"
    exts:
      - ".exe"
      - ".dll"
      - ".scr"
      - ".js"
      - ".vbs"
      - ".ps1"
      - ".hta"
      - ".jar"
      - ".bat"
      - ".cmd"

outbound:
  mode: "https"   # UI + backend expect HTTPS collector mode
  https:
    url: "http://127.0.0.1:8000/ingest"   # must end with /ingest (your backend check)
    cafile: ""                            # blank for local HTTP
  mqtt:                                    # kept for future use; harmless to keep
    host: "localhost"
    port: 8883
    username: "rtm_agent"
    password: "REDACTED"
    cafile: "..\\deploy\\tls\\ca.crt"

security:
  hmac_key_env: "RTM_HMAC_KEY"
